spring.datasource.url=jdbc:postgresql://localhost:5432/Gym_Elite
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

gym.app.url=http://test-gym-app/api/payments/webhook
